/* ===========================================================
   Sample IELTS content. Edit/expand this file with real data —
   the app just reads these arrays/objects, no schema migration needed.
   =========================================================== */
const DATA = {
  vocabTopics: [
    {
      id: 'environment',
      name: 'Môi trường',
      emoji: '🌱',
      words: [
        { id: 'env-1', word: 'sustainable', phonetic: '/səˈsteɪnəbl/', meaning: 'bền vững', example: 'We need sustainable energy sources.' },
        { id: 'env-2', word: 'deforestation', phonetic: '/diːˌfɒrɪˈsteɪʃn/', meaning: 'nạn phá rừng', example: 'Deforestation contributes to climate change.' },
        { id: 'env-3', word: 'emission', phonetic: '/ɪˈmɪʃn/', meaning: 'sự phát thải', example: 'Carbon emissions must be reduced.' },
        { id: 'env-4', word: 'renewable', phonetic: '/rɪˈnjuːəbl/', meaning: 'có thể tái tạo', example: 'Solar power is a renewable resource.' },
        { id: 'env-5', word: 'pollution', phonetic: '/pəˈluːʃn/', meaning: 'ô nhiễm', example: 'Air pollution affects public health.' },
        { id: 'env-6', word: 'ecosystem', phonetic: '/ˈiːkoʊsɪstəm/', meaning: 'hệ sinh thái', example: 'Coral reefs support a diverse ecosystem.' },
        { id: 'env-7', word: 'biodiversity', phonetic: '/ˌbaɪoʊdaɪˈvɜːrsəti/', meaning: 'đa dạng sinh học', example: 'The rainforest has incredible biodiversity.' },
        { id: 'env-8', word: 'greenhouse gas', phonetic: '/ˈɡriːnhaʊs ɡæs/', meaning: 'khí nhà kính', example: 'Greenhouse gases trap heat in the atmosphere.' },
        { id: 'env-9', word: 'conservation', phonetic: '/ˌkɒnsərˈveɪʃn/', meaning: 'sự bảo tồn', example: 'Wildlife conservation efforts saved the species.' },
        { id: 'env-10', word: 'drought', phonetic: '/draʊt/', meaning: 'hạn hán', example: 'The region suffered a severe drought last summer.' },
        { id: 'env-11', word: 'depletion', phonetic: '/dɪˈpliːʃn/', meaning: 'sự cạn kiệt', example: 'Ozone depletion is a global concern.' },
        { id: 'env-12', word: 'habitat', phonetic: '/ˈhæbɪtæt/', meaning: 'môi trường sống', example: 'Urban expansion destroys natural habitats.' },
      ],
    },
    {
      id: 'education',
      name: 'Giáo dục',
      emoji: '🎓',
      words: [
        { id: 'edu-1', word: 'curriculum', phonetic: '/kəˈrɪkjələm/', meaning: 'chương trình học', example: 'The school updated its curriculum.' },
        { id: 'edu-2', word: 'literacy', phonetic: '/ˈlɪtərəsi/', meaning: 'khả năng đọc viết', example: 'Adult literacy rates have improved.' },
        { id: 'edu-3', word: 'scholarship', phonetic: '/ˈskɒlərʃɪp/', meaning: 'học bổng', example: 'She was awarded a full scholarship.' },
        { id: 'edu-4', word: 'assessment', phonetic: '/əˈsesmənt/', meaning: 'sự đánh giá', example: 'Continuous assessment is used in this course.' },
        { id: 'edu-5', word: 'undergraduate', phonetic: '/ˌʌndərˈɡrædʒuət/', meaning: 'sinh viên đại học', example: 'He is an undergraduate at a top university.' },
        { id: 'edu-6', word: 'tuition fee', phonetic: '/tjuˈɪʃn fiː/', meaning: 'học phí', example: 'Tuition fees have risen this year.' },
        { id: 'edu-7', word: 'vocational training', phonetic: '/voʊˈkeɪʃənl ˈtreɪnɪŋ/', meaning: 'đào tạo nghề', example: 'Vocational training prepares students for skilled jobs.' },
        { id: 'edu-8', word: 'rote learning', phonetic: '/roʊt ˈlɜːrnɪŋ/', meaning: 'học vẹt', example: 'Rote learning discourages critical thinking.' },
        { id: 'edu-9', word: 'peer pressure', phonetic: '/pɪr ˈpreʃər/', meaning: 'áp lực từ bạn bè', example: 'Peer pressure can influence a student’s choices.' },
        { id: 'edu-10', word: 'extracurricular', phonetic: '/ˌekstrəkəˈrɪkjələr/', meaning: 'ngoại khóa', example: 'Extracurricular activities build teamwork skills.' },
      ],
    },
    {
      id: 'technology',
      name: 'Công nghệ',
      emoji: '💻',
      words: [
        { id: 'tech-1', word: 'innovation', phonetic: '/ˌɪnəˈveɪʃn/', meaning: 'sự đổi mới', example: 'Technological innovation drives the economy.' },
        { id: 'tech-2', word: 'artificial intelligence', phonetic: '/ˌɑːrtɪˈfɪʃl ɪnˈtelɪdʒəns/', meaning: 'trí tuệ nhân tạo', example: 'Artificial intelligence is transforming industries.' },
        { id: 'tech-3', word: 'automation', phonetic: '/ˌɔːtəˈmeɪʃn/', meaning: 'tự động hóa', example: 'Automation has replaced many manual jobs.' },
        { id: 'tech-4', word: 'infrastructure', phonetic: '/ˈɪnfrəstrʌktʃər/', meaning: 'cơ sở hạ tầng', example: 'The country invested in digital infrastructure.' },
        { id: 'tech-5', word: 'cybersecurity', phonetic: '/ˈsaɪbərsɪˌkjʊrəti/', meaning: 'an ninh mạng', example: 'Companies spend heavily on cybersecurity.' },
        { id: 'tech-6', word: 'connectivity', phonetic: '/ˌkɒnekˈtɪvəti/', meaning: 'khả năng kết nối', example: 'Rural connectivity remains a challenge.' },
        { id: 'tech-7', word: 'obsolete', phonetic: '/ˈɒbsəliːt/', meaning: 'lỗi thời', example: 'Many devices become obsolete within a few years.' },
        { id: 'tech-8', word: 'breakthrough', phonetic: '/ˈbreɪkθruː/', meaning: 'bước đột phá', example: 'Scientists made a breakthrough in battery technology.' },
        { id: 'tech-9', word: 'data privacy', phonetic: '/ˈdeɪtə ˈpraɪvəsi/', meaning: 'quyền riêng tư dữ liệu', example: 'Data privacy laws protect personal information.' },
        { id: 'tech-10', word: 'streamline', phonetic: '/ˈstriːmlaɪn/', meaning: 'hợp lý hóa, tinh gọn', example: 'The app streamlines the ordering process.' },
      ],
    },
    {
      id: 'health',
      name: 'Sức khỏe',
      emoji: '🏥',
      words: [
        { id: 'hea-1', word: 'nutrition', phonetic: '/njuˈtrɪʃn/', meaning: 'dinh dưỡng', example: 'Good nutrition is essential for children.' },
        { id: 'hea-2', word: 'obesity', phonetic: '/oʊˈbiːsəti/', meaning: 'bệnh béo phì', example: 'Obesity rates have risen sharply.' },
        { id: 'hea-3', word: 'epidemic', phonetic: '/ˌepɪˈdemɪk/', meaning: 'dịch bệnh', example: 'The country faced a flu epidemic.' },
        { id: 'hea-4', word: 'well-being', phonetic: '/ˈwel biːɪŋ/', meaning: 'sự khỏe mạnh, hạnh phúc', example: 'Exercise improves mental well-being.' },
        { id: 'hea-5', word: 'sedentary', phonetic: '/ˈsednteri/', meaning: 'ít vận động', example: 'A sedentary lifestyle increases health risks.' },
        { id: 'hea-6', word: 'immune system', phonetic: '/ɪˈmjuːn ˈsɪstəm/', meaning: 'hệ miễn dịch', example: 'Vitamin C boosts the immune system.' },
        { id: 'hea-7', word: 'chronic', phonetic: '/ˈkrɒnɪk/', meaning: 'mãn tính', example: 'Diabetes is a chronic condition.' },
        { id: 'hea-8', word: 'life expectancy', phonetic: '/laɪf ɪkˈspektənsi/', meaning: 'tuổi thọ trung bình', example: 'Life expectancy has increased worldwide.' },
        { id: 'hea-9', word: 'mental disorder', phonetic: '/ˈmentl dɪsˈɔːrdər/', meaning: 'rối loạn tâm lý', example: 'Mental disorders are becoming more widely discussed.' },
        { id: 'hea-10', word: 'vaccination', phonetic: '/ˌvæksɪˈneɪʃn/', meaning: 'sự tiêm chủng', example: 'Vaccination programs reduced disease outbreaks.' },
      ],
    },
    {
      id: 'work',
      name: 'Công việc',
      emoji: '💼',
      words: [
        { id: 'work-1', word: 'workforce', phonetic: '/ˈwɜːrkfɔːrs/', meaning: 'lực lượng lao động', example: 'The workforce is becoming more diverse.' },
        { id: 'work-2', word: 'redundancy', phonetic: '/rɪˈdʌndənsi/', meaning: 'sự dư thừa, sa thải', example: 'The factory announced widespread redundancies.' },
        { id: 'work-3', word: 'productivity', phonetic: '/ˌproʊdʌkˈtɪvəti/', meaning: 'năng suất', example: 'Remote work can boost productivity.' },
        { id: 'work-4', word: 'work-life balance', phonetic: '/wɜːrk laɪf ˈbæləns/', meaning: 'cân bằng công việc-cuộc sống', example: 'Employees value work-life balance highly.' },
        { id: 'work-5', word: 'promotion', phonetic: '/prəˈmoʊʃn/', meaning: 'sự thăng chức', example: 'She earned a promotion after two years.' },
        { id: 'work-6', word: 'entrepreneur', phonetic: '/ˌɒntrəprəˈnɜːr/', meaning: 'doanh nhân khởi nghiệp', example: 'Young entrepreneurs are starting more tech firms.' },
        { id: 'work-7', word: 'freelance', phonetic: '/ˈfriːlæns/', meaning: 'làm việc tự do', example: 'He works as a freelance designer.' },
        { id: 'work-8', word: 'job security', phonetic: '/dʒɒb sɪˈkjʊrəti/', meaning: 'sự ổn định công việc', example: 'Job security is a top concern for workers.' },
      ],
    },
    {
      id: 'society',
      name: 'Xã hội',
      emoji: '🏙️',
      words: [
        { id: 'soc-1', word: 'urbanization', phonetic: '/ˌɜːrbənaɪˈzeɪʃn/', meaning: 'đô thị hóa', example: 'Rapid urbanization strains public services.' },
        { id: 'soc-2', word: 'inequality', phonetic: '/ˌɪnɪˈkwɒləti/', meaning: 'sự bất bình đẳng', example: 'Income inequality has widened in many countries.' },
        { id: 'soc-3', word: 'community', phonetic: '/kəˈmjuːnəti/', meaning: 'cộng đồng', example: 'The community organized a charity event.' },
        { id: 'soc-4', word: 'diversity', phonetic: '/daɪˈvɜːrsəti/', meaning: 'sự đa dạng', example: 'Cultural diversity enriches society.' },
        { id: 'soc-5', word: 'poverty', phonetic: '/ˈpɒvərti/', meaning: 'sự nghèo đói', example: 'The program aims to reduce poverty.' },
        { id: 'soc-6', word: 'migration', phonetic: '/maɪˈɡreɪʃn/', meaning: 'sự di cư', example: 'Migration to cities continues to grow.' },
        { id: 'soc-7', word: 'welfare', phonetic: '/ˈwelfeər/', meaning: 'phúc lợi xã hội', example: 'The government expanded welfare benefits.' },
        { id: 'soc-8', word: 'discrimination', phonetic: '/dɪˌskrɪmɪˈneɪʃn/', meaning: 'sự phân biệt đối xử', example: 'Laws exist to prevent workplace discrimination.' },
      ],
    },
    {
      id: 'travel',
      name: 'Du lịch',
      emoji: '✈️',
      words: [
        { id: 'trv-1', word: 'itinerary', phonetic: '/aɪˈtɪnəreri/', meaning: 'lịch trình', example: 'We planned a detailed itinerary for the trip.' },
        { id: 'trv-2', word: 'accommodation', phonetic: '/əˌkɒməˈdeɪʃn/', meaning: 'chỗ ở', example: 'Accommodation prices rise during peak season.' },
        { id: 'trv-3', word: 'heritage site', phonetic: '/ˈherɪtɪdʒ saɪt/', meaning: 'di sản', example: 'The temple is a UNESCO heritage site.' },
        { id: 'trv-4', word: 'excursion', phonetic: '/ɪkˈskɜːrʒn/', meaning: 'chuyến du ngoạn', example: 'We took a day excursion to the coast.' },
        { id: 'trv-5', word: 'sustainable tourism', phonetic: '/səˈsteɪnəbl ˈtʊrɪzəm/', meaning: 'du lịch bền vững', example: 'Sustainable tourism protects local ecosystems.' },
        { id: 'trv-6', word: 'landmark', phonetic: '/ˈlændmɑːrk/', meaning: 'địa danh, mốc nổi bật', example: 'The tower is a famous landmark.' },
        { id: 'trv-7', word: 'domestic tourism', phonetic: '/dəˈmestɪk ˈtʊrɪzəm/', meaning: 'du lịch nội địa', example: 'Domestic tourism grew during the holidays.' },
      ],
    },
    {
      id: 'economy',
      name: 'Kinh tế',
      emoji: '💰',
      words: [
        { id: 'eco-1', word: 'inflation', phonetic: '/ɪnˈfleɪʃn/', meaning: 'lạm phát', example: 'Inflation has pushed prices higher.' },
        { id: 'eco-2', word: 'recession', phonetic: '/rɪˈseʃn/', meaning: 'suy thoái kinh tế', example: 'The country entered a recession last year.' },
        { id: 'eco-3', word: 'investment', phonetic: '/ɪnˈvestmənt/', meaning: 'đầu tư', example: 'Foreign investment boosted local industries.' },
        { id: 'eco-4', word: 'subsidy', phonetic: '/ˈsʌbsədi/', meaning: 'trợ cấp', example: 'Farmers receive government subsidies.' },
        { id: 'eco-5', word: 'trade deficit', phonetic: '/treɪd ˈdefɪsɪt/', meaning: 'thâm hụt thương mại', example: 'The trade deficit widened this quarter.' },
        { id: 'eco-6', word: 'consumer spending', phonetic: '/kənˈsjuːmər ˈspendɪŋ/', meaning: 'chi tiêu tiêu dùng', example: 'Consumer spending drives economic growth.' },
        { id: 'eco-7', word: 'revenue', phonetic: '/ˈrevənjuː/', meaning: 'doanh thu', example: 'The company’s revenue doubled this year.' },
      ],
    },
    {
      id: 'crime',
      name: 'Tội phạm & Luật pháp',
      emoji: '⚖️',
      words: [
        { id: 'crm-1', word: 'offender', phonetic: '/əˈfendər/', meaning: 'người phạm tội', example: 'First-time offenders often receive lighter sentences.' },
        { id: 'crm-2', word: 'deterrent', phonetic: '/dɪˈtɜːrənt/', meaning: 'biện pháp răn đe', example: 'Harsh penalties act as a deterrent.' },
        { id: 'crm-3', word: 'rehabilitation', phonetic: '/ˌriːəˌbɪlɪˈteɪʃn/', meaning: 'sự cải tạo, phục hồi', example: 'Rehabilitation programs help reduce reoffending.' },
        { id: 'crm-4', word: 'surveillance', phonetic: '/sərˈveɪləns/', meaning: 'sự giám sát', example: 'CCTV surveillance has increased in cities.' },
        { id: 'crm-5', word: 'legislation', phonetic: '/ˌledʒɪsˈleɪʃn/', meaning: 'luật pháp, đạo luật', example: 'New legislation targets cybercrime.' },
        { id: 'crm-6', word: 'juvenile delinquency', phonetic: '/ˈdʒuːvənaɪl dɪˈlɪŋkwənsi/', meaning: 'tội phạm vị thành niên', example: 'Juvenile delinquency is linked to poverty.' },
      ],
    },
    {
      id: 'media',
      name: 'Truyền thông',
      emoji: '📱',
      words: [
        { id: 'med-1', word: 'censorship', phonetic: '/ˈsensərʃɪp/', meaning: 'sự kiểm duyệt', example: 'Censorship limits free expression.' },
        { id: 'med-2', word: 'misinformation', phonetic: '/ˌmɪsɪnfərˈmeɪʃn/', meaning: 'thông tin sai lệch', example: 'Misinformation spreads quickly on social media.' },
        { id: 'med-3', word: 'broadcast', phonetic: '/ˈbrɔːdkæst/', meaning: 'phát sóng', example: 'The event was broadcast live worldwide.' },
        { id: 'med-4', word: 'tabloid', phonetic: '/ˈtæblɔɪd/', meaning: 'báo lá cải', example: 'Tabloid newspapers focus on sensational stories.' },
        { id: 'med-5', word: 'influencer', phonetic: '/ˈɪnfluənsər/', meaning: 'người có sức ảnh hưởng', example: 'Influencers shape consumer trends online.' },
        { id: 'med-6', word: 'credibility', phonetic: '/ˌkredəˈbɪləti/', meaning: 'độ tin cậy', example: 'The source’s credibility was questioned.' },
      ],
    },
  ],

  grammarTopics: [
    {
      id: 'conditionals',
      name: 'Câu điều kiện',
      emoji: '🔀',
      theory: 'Câu điều kiện loại 2 diễn tả tình huống giả định không có thật ở hiện tại: If + S + V(quá khứ), S + would + V(nguyên mẫu). Ví dụ: If I had more time, I would travel more. Câu điều kiện loại 3 diễn tả điều không có thật trong quá khứ: If + S + had + V3, S + would have + V3.',
      exercises: [
        { id: 'cond-1', question: 'If she ___ (have) more money, she would buy a house.', options: ['has', 'had', 'have', 'having'], answer: 1 },
        { id: 'cond-2', question: 'If it rains, we ___ (stay) at home.', options: ['will stay', 'would stay', 'stayed', 'stay'], answer: 0 },
        { id: 'cond-3', question: 'If I had studied harder, I ___ (pass) the exam.', options: ['would pass', 'would have passed', 'passed', 'will pass'], answer: 1 },
        { id: 'cond-4', question: 'If they ___ (leave) earlier, they wouldn’t have missed the bus.', options: ['leave', 'left', 'had left', 'leaving'], answer: 2 },
      ],
    },
    {
      id: 'passive',
      name: 'Câu bị động',
      emoji: '🔁',
      theory: 'Câu bị động dùng khi nhấn mạnh vào đối tượng chịu tác động của hành động: S + be + V3/ed. Ví dụ: The report was written by the team.',
      exercises: [
        { id: 'pas-1', question: 'The letter ___ (send) yesterday.', options: ['was sent', 'sent', 'is sent', 'sending'], answer: 0 },
        { id: 'pas-2', question: 'This bridge ___ (build) in 1990.', options: ['built', 'was built', 'is built', 'builds'], answer: 1 },
        { id: 'pas-3', question: 'The new policy ___ (announce) next week.', options: ['will be announced', 'will announce', 'announced', 'is announcing'], answer: 0 },
        { id: 'pas-4', question: 'English ___ (speak) in many countries.', options: ['speaks', 'is spoken', 'spoke', 'is speaking'], answer: 1 },
      ],
    },
    {
      id: 'relative-clauses',
      name: 'Mệnh đề quan hệ',
      emoji: '🔗',
      theory: 'Mệnh đề quan hệ bổ nghĩa cho danh từ đứng trước, dùng who/which/that/whose. Ví dụ: The book that I bought is interesting.',
      exercises: [
        { id: 'rel-1', question: 'The man ___ lives next door is a doctor.', options: ['which', 'who', 'whose', 'where'], answer: 1 },
        { id: 'rel-2', question: 'This is the house ___ roof was damaged.', options: ['who', 'which', 'whose', 'that'], answer: 2 },
        { id: 'rel-3', question: 'The city ___ I was born has changed a lot.', options: ['who', 'which', 'where', 'whose'], answer: 2 },
      ],
    },
    {
      id: 'comparatives',
      name: 'So sánh',
      emoji: '📊',
      theory: 'So sánh hơn: adj-er / more + adj + than. So sánh nhất: the + adj-est / the most + adj. Ví dụ: This course is more difficult than the last one. It is the most useful subject at school.',
      exercises: [
        { id: 'cmp-1', question: 'This exam is ___ (difficult) than the previous one.', options: ['more difficult', 'difficulter', 'most difficult', 'difficult'], answer: 0 },
        { id: 'cmp-2', question: 'She is the ___ (talented) student in the class.', options: ['more talented', 'talenteder', 'most talented', 'talented'], answer: 2 },
        { id: 'cmp-3', question: 'Traffic in the city is getting ___ (bad) every year.', options: ['worse', 'more bad', 'baddest', 'worst'], answer: 0 },
      ],
    },
    {
      id: 'reported-speech',
      name: 'Câu tường thuật',
      emoji: '💬',
      theory: 'Khi tường thuật lại lời nói, động từ thường lùi một thì so với câu trực tiếp. Ví dụ: "I am tired," she said. → She said (that) she was tired.',
      exercises: [
        { id: 'rep-1', question: '"I will call you," he said. → He said he ___ call me.', options: ['will', 'would', 'can', 'shall'], answer: 1 },
        { id: 'rep-2', question: '"I am studying," she said. → She said she ___ studying.', options: ['is', 'was', 'has been', 'were'], answer: 1 },
        { id: 'rep-3', question: '"I have finished," he said. → He said he ___ finished.', options: ['has', 'have', 'had', 'having'], answer: 2 },
      ],
    },
    {
      id: 'modal-verbs',
      name: 'Động từ khuyết thiếu',
      emoji: '🧠',
      theory: 'Động từ khuyết thiếu (must, should, might, can) diễn tả nghĩa vụ, lời khuyên, khả năng. Ví dụ: You should exercise regularly. It might rain later.',
      exercises: [
        { id: 'mod-1', question: 'You ___ smoke in the hospital. It’s forbidden.', options: ['must', 'mustn’t', 'should', 'can'], answer: 1 },
        { id: 'mod-2', question: 'She ___ be at home; her car is in the driveway.', options: ['must', 'might', 'can', 'should'], answer: 0 },
        { id: 'mod-3', question: 'You ___ see a doctor if the pain continues.', options: ['should', 'can', 'must have', 'need'], answer: 0 },
      ],
    },
  ],

  // Reading/Listening style MCQ pool, auto-gradable.
  quizPool: [
    { id: 'q1', question: 'The company decided to ___ its operations to reduce costs.', options: ['streamline', 'complicate', 'expand', 'ignore'], answer: 0, topic: 'technology' },
    { id: 'q2', question: 'Choose the synonym for "abundant".', options: ['scarce', 'plentiful', 'limited', 'rare'], answer: 1, topic: 'environment' },
    { id: 'q3', question: 'Which word best completes: "The findings were based on rigorous ___"?', options: ['research', 'guessing', 'opinion', 'rumor'], answer: 0, topic: 'education' },
    { id: 'q4', question: '"Sedentary lifestyle" is most closely associated with which issue?', options: ['obesity', 'literacy', 'pollution', 'innovation'], answer: 0, topic: 'health' },
    { id: 'q5', question: 'Choose the correct word: The government introduced new policies to ___ carbon emissions.', options: ['increase', 'cut', 'ignore', 'celebrate'], answer: 1, topic: 'environment' },
    { id: 'q6', question: '"Undergraduate" refers to a student who is studying for their ___ degree.', options: ['first', 'second', 'doctoral', 'honorary'], answer: 0, topic: 'education' },
    { id: 'q7', question: 'Choose the synonym for "redundancy" in a work context.', options: ['promotion', 'job loss', 'bonus', 'training'], answer: 1, topic: 'work' },
    { id: 'q8', question: 'Which word best fits: "Rapid ___ has led to overcrowded cities."', options: ['urbanization', 'conservation', 'literacy', 'inflation'], answer: 0, topic: 'society' },
    { id: 'q9', question: 'A "heritage site" is best described as a place that is ___.', options: ['newly built', 'historically significant', 'abandoned', 'privately owned'], answer: 1, topic: 'travel' },
    { id: 'q10', question: 'Choose the correct word: High ___ makes everyday goods more expensive.', options: ['inflation', 'investment', 'subsidy', 'revenue'], answer: 0, topic: 'economy' },
    { id: 'q11', question: '"Rehabilitation" in the justice system mainly aims to ___ offenders.', options: ['punish', 'reform', 'imprison', 'ignore'], answer: 1, topic: 'crime' },
    { id: 'q12', question: 'Choose the synonym for "misinformation".', options: ['false news', 'breaking news', 'headline', 'editorial'], answer: 0, topic: 'media' },
    { id: 'q13', question: 'Which word best completes: "The species lost its natural ___ due to logging."', options: ['habitat', 'emission', 'drought', 'depletion'], answer: 0, topic: 'environment' },
    { id: 'q14', question: '"Tuition fee" refers to money paid for ___.', options: ['housing', 'education', 'transport', 'food'], answer: 1, topic: 'education' },
    { id: 'q15', question: 'Choose the correct word: The app was designed to improve user ___.', options: ['obsolescence', 'connectivity', 'depletion', 'discrimination'], answer: 1, topic: 'technology' },
  ],

  // Full mock test: reading + listening MCQ sets, band-scored.
  mockTest: {
    reading: [
      { id: 'mr1', passage: 'Renewable energy sources such as solar and wind are becoming more cost-effective every year, prompting many countries to shift away from fossil fuels.', question: 'What is prompting countries to shift energy sources?', options: ['Cost-effectiveness of renewables', 'Government bans', 'Public protests', 'Lack of oil'], answer: 0 },
      { id: 'mr2', passage: 'Despite improvements in literacy programs, many rural areas still lack access to quality education, widening the gap between urban and rural students.', question: 'What problem persists in rural areas?', options: ['Overcrowded schools', 'Lack of access to quality education', 'Too many teachers', 'High literacy'], answer: 1 },
      { id: 'mr3', passage: 'As remote work becomes more common, many employees report higher productivity but also greater difficulty separating work from personal life.', question: 'What challenge do remote workers report?', options: ['Lower pay', 'Separating work and personal life', 'Lack of technology', 'Too much supervision'], answer: 1 },
      { id: 'mr4', passage: 'Urban planners are increasingly designing cities around public transport and cycling to reduce traffic congestion and air pollution.', question: 'Why are cities being redesigned around public transport?', options: ['To increase car sales', 'To reduce congestion and pollution', 'To attract tourists', 'To build more parking'], answer: 1 },
      { id: 'mr5', passage: 'A recent study found that students who engage in extracurricular activities tend to develop stronger teamwork and communication skills than those who do not.', question: 'What benefit is linked to extracurricular activities?', options: ['Higher exam scores only', 'Stronger teamwork and communication skills', 'Less homework', 'Shorter school days'], answer: 1 },
    ],
    listening: [
      { id: 'ml1', audioText: '(Đoạn hội thoại) A: Are you attending the conference next week? B: Yes, I registered for the technology and innovation panel.', question: 'Which panel did B register for?', options: ['Health', 'Technology and innovation', 'Environment', 'Education'], answer: 1 },
      { id: 'ml2', audioText: '(Thông báo) Please note that due to renovation, the library will be closed until further notice.', question: 'Why is the library closed?', options: ['Renovation', 'Holiday', 'Flooding', 'Staff shortage'], answer: 0 },
      { id: 'ml3', audioText: '(Đoạn hội thoại) A: How was your trip to the coast? B: Great, but the accommodation was more expensive than we expected.', question: 'What surprised B about the trip?', options: ['The weather', 'The cost of accommodation', 'The distance', 'The food'], answer: 1 },
      { id: 'ml4', audioText: '(Thông báo) All students must submit their scholarship applications online before the end of the month.', question: 'What must students do before the end of the month?', options: ['Attend a meeting', 'Submit scholarship applications', 'Pay tuition fees', 'Register for classes'], answer: 1 },
    ],
  },

  // Writing/Speaking are not auto-graded — shown as tips + prompts.
  writingPrompts: [
    { id: 'w1', task: 'Task 2', prompt: 'Some people believe technology has made life more complex. To what extent do you agree or disagree?', tips: ['Nêu rõ quan điểm ngay ở mở bài.', 'Dùng ví dụ cụ thể để minh họa.', 'Kết bài tóm tắt lại lập trường.'] },
    { id: 'w2', task: 'Task 1', prompt: 'The chart below shows the percentage of households with internet access in three countries from 2000 to 2020. Summarize the information.', tips: ['Nêu xu hướng tổng quát trước.', 'So sánh số liệu nổi bật, không liệt kê hết.', 'Không đưa ý kiến cá nhân.'] },
    { id: 'w3', task: 'Task 2', prompt: 'Many people think that university education should be free for everyone. Discuss both views and give your own opinion.', tips: ['Trình bày cả hai quan điểm trước khi nêu ý kiến cá nhân.', 'Mỗi đoạn thân bài chỉ nên tập trung một ý chính.', 'Dùng từ nối để liên kết ý mạch lạc.'] },
    { id: 'w4', task: 'Task 2', prompt: 'Some argue that governments should invest more in public transport rather than building new roads. To what extent do you agree?', tips: ['Đưa ra lý do cụ thể cho quan điểm của bạn.', 'Cân nhắc phản biện để bài viết cân bằng hơn.', 'Kết luận rõ ràng, nhất quán với mở bài.'] },
  ],
  speakingPrompts: [
    { id: 's1', part: 'Part 2', prompt: 'Describe a piece of technology you find useful. You should say what it is, how you use it, and explain why you find it useful.', tips: ['Dùng cấu trúc: giới thiệu – mô tả – lý do.', 'Nói trong 1-2 phút, không dừng lâu.'] },
    { id: 's2', part: 'Part 3', prompt: 'Do you think technology has changed the way people communicate?', tips: ['Đưa quan điểm rõ ràng.', 'Giải thích bằng ví dụ thực tế.'] },
    { id: 's3', part: 'Part 2', prompt: 'Describe a memorable trip you took. You should say where you went, who you went with, and explain why it was memorable.', tips: ['Sắp xếp ý theo trình tự thời gian.', 'Thêm cảm xúc cá nhân để câu trả lời sinh động hơn.'] },
    { id: 's4', part: 'Part 3', prompt: 'What are the benefits of tourism for a country’s economy?', tips: ['Nêu ít nhất hai lợi ích cụ thể.', 'Liên hệ với ví dụ thực tế nếu có thể.'] },
    { id: 's5', part: 'Part 1', prompt: 'What do you usually do to stay healthy?', tips: ['Trả lời ngắn gọn, tự nhiên trong 20-30 giây.', 'Mở rộng câu trả lời bằng một lý do hoặc ví dụ.'] },
  ],

  // Short rotating study tips for the home-screen ticker.
  tips: [
    '💡 Học 10 từ vựng mỗi ngày đều hơn là 70 từ một lần.',
    '💡 Ghi âm giọng nói của bạn khi luyện Speaking để tự nghe lại.',
    '💡 Đọc lại lý thuyết ngữ pháp trước khi làm bài tập.',
    '💡 Trong Reading, đọc câu hỏi trước khi đọc đoạn văn.',
    '💡 Ôn từ vựng đã học 24 giờ sau khi học lần đầu để nhớ lâu hơn.',
    '💡 Viết Task 2 trong đúng 40 phút để quen áp lực thời gian thi thật.',
    '💡 Nghe tin tức tiếng Anh mỗi ngày để làm quen nhiều giọng đọc.',
  ],

  achievements: [
    { id: 'b1', name: 'Khởi động', emoji: '🌟', condition: p => p.vocabDone >= 1 },
    { id: 'b2', name: '10 từ vựng', emoji: '📚', condition: p => p.vocabDone >= 10 },
    { id: 'b3', name: '50 từ vựng', emoji: '📖', condition: p => p.vocabDone >= 50 },
    { id: 'b4', name: 'Quiz thủ', emoji: '🎯', condition: p => p.quizDone >= 5 },
    { id: 'b5', name: 'Ngữ pháp gia', emoji: '📝', condition: p => p.grammarDone >= 5 },
    { id: 'b6', name: 'Mock test đầu tiên', emoji: '🏆', condition: p => p.mockTests.length >= 1 },
    { id: 'b7', name: 'Band 7+', emoji: '🔥', condition: p => p.mockTests.some(m => m.band >= 7) },
    { id: 'b8', name: 'Band 8+', emoji: '💎', condition: p => p.mockTests.some(m => m.band >= 8) },
    { id: 'b9', name: 'Chăm chỉ', emoji: '⚡', condition: p => p.mockTests.length >= 3 },
  ],
};
